version: '3'
services:
  flask-scanner:
    build:
      context: ./flask-app
    container_name: flask-scanner
    expose:
      - "5000"
    networks:
      - sbom-net

  nginx-frontend:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "12345:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask-scanner
    networks:
      - sbom-net

networks:
  sbom-net:
